RedHatQE/notify-service

- README.md
- chart/templates/deployment.yaml
- chart/templates/pvc.yaml
- chart/values.yaml
User could config pvc and mount path for templates.
> Add pvc for templates

- app/api/endpoints/chat.py
- app/api/endpoints/email.py
- app/api/endpoints/irc.py
- app/api/endpoints/message_bus.py
- app/api/endpoints/template.py
- app/api/endpoints/utils.py
Add description for each parameter of different types.
> Add parameters description for APIs

- app/api/api.py
- app/api/endpoints/chat.py
- app/api/endpoints/irc.py
- app/api/endpoints/message.py
- app/utils/irc.py
- app/utils/message_bus.py
- Add new multi target message api
- Fix IRC message too long error
- Remove sys.exit in message bus utils
> Add new multi target message api

- app/api/endpoints/chat.py
- app/api/endpoints/email.py
- app/api/endpoints/irc.py
- app/api/endpoints/message.py
- app/api/endpoints/message_bus.py
- app/schemas/__init__.py
- app/schemas/msg.py
- app/utils/message_bus.py
Add new TextBody and DictBody schema for request body, use Union for
support multiple schemas.
Update apis with the schemas, this change api behavior with 'body'
key is required in request body.
Also update examples for request body.
> Update request body schemas

- app/api/endpoints/chat.py
Seperate text message to multiple messages if exceed 4096.
> Avoid GChat text message 4096 characters limitation

- app/templates/build/default.html
- app/templates/build/newsletter.html
- app/templates/build/newsletter_body.json
- app/templates/src/default.mjml
- app/templates/src/newsletter.mjml
Update default template and add newsletter template.
All generate with mjml.io live.
> Update email templates

- app/api/endpoints/chat.py
- app/api/endpoints/email.py
- app/api/endpoints/message.py
- app/templates/build/teflo_scenario_email.html
- app/templates/build/teflo_scenario_gchat.jinja
- app/templates/build/teflo_scenario_slack.jinja
- app/templates/src/teflo_scenario_email.mjml
- app/utils/utils.py
- docs/sample/teflo_scenario_email_gchat_slack.json
- docs/sample/teflo_scenario_gchat_slack.json
Add templates for gchat, slack and email.
The templates are based on:
- gchat_template.jinja
- slack_template.jinja
from project:
https://github.com/RedHatQE/teflo_webhooks_notification_plugin
> Add Teflo templates

- app/templates/build/teflo_scenario_email.html
- app/templates/src/teflo_scenario_email.mjml
This fixes issue:
https://github.com/waynesun09/notify-service/issues/25
> Update teflo email template

- app/api/endpoints/chat.py
- app/api/endpoints/email.py
- app/api/endpoints/message.py
Update multi target message api with template urls parameters.
Also fix a typo.
This resolve RFE:
https://github.com/waynesun09/notify-service/issues/24
> Add template url query parameters

- .github/workflows/build.yml
- .test.env
- Dockerfile
- Dockerfile.dev
- README.md
- app/schemas/result.py
- app/tests/__init__.py
- app/tests/api/api_v1/test_chat.py
- app/tests/api/api_v1/test_email.py
- app/tests/api/api_v1/test_irc.py
- app/tests/api/api_v1/test_message.py
- app/tests/api/api_v1/test_message_bus.py
- app/tests/api/api_v1/test_template.py
- app/tests/conftest.py
- docs/development.md
- Add basic unit tests for all apis 
- Patch cache dependencies in test
- Update doc and github action
> Add unit tests for the apis

- Pipfile.lock
> Update pipenv lock

- .github/workflows/flak8.yml
- Dockerfile
- Pipfile
- README.md
Update python dependency to 3.9.
> Update Python version to 3.9

- Pipfile
- Pipfile.lock
- app/main.py
Update ujson >=5.1.0 and other packages to latest
> Update package dependencies 

- app/main.py
This reverts commit de8a322999a69e72384c8119112823f2fa70ff3d.
The path have been removed in new fastapi version.
> Revert "Fix custom_openapi parameter issue"

- app/api/endpoints/message.py
- app/tests/api/api_v1/test_message.py
Signed-off-by: Ido Burstein <idoburstein@gmail.com>
> Add Bugzilla functionality to multi-message module

- README.md
Signed-off-by: Ido Burstein <idoburstein@gmail.com> @waynesun09
> Update Helm doc for jira and bugzilla parameters

- README.md
- app/api/endpoints/bugzilla_endpoint.py
- app/api/endpoints/chat.py
- app/api/endpoints/email.py
- app/api/endpoints/jira.py
- app/api/endpoints/message.py
- app/main.py
- app/templates/build/default.html
- app/templates/build/newsletter.html
- app/templates/build/teflo_scenario_email.html
- app/templates/src/default.mjml
- app/templates/src/newsletter.mjml
- app/templates/src/teflo_scenario_email.mjml
- docs/sample/newsletter.json
- docs/sample/teflo_scenario_email_gchat_slack_jira_bugzilla.json
> Update the doc urls in code and docs

- chart/templates/deployment.yaml
- chart/values.yaml
Signed-off-by: Ido Burstein iburstei@redhat.com @waynesun09
> Update redis helm chart values

- Pipfile.lock
> Bump dependency versions

- Pipfile.lock
Resovle redis issue:
- CVE-2023-28858
- CVE-2023-28859
> Bump dependency version

- .github/workflows/build.yml
- .github/workflows/flak8.yml
- .pre-commit-config.yaml
- Dockerfile
- Pipfile
- Pipfile.lock
Update python and all dependencies
> Bump python to 3.11
